name: Deploy
on: 'push'

env:
  CF_EMAIL: ${{ secrets.CF_EMAIL }}
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked

      - name: Create wrangler.toml
        run: ./scripts/make-wrangler.sh prod

      - name: Publish
        run: ./scripts/publish.sh
